# Generated by Django 2.2 on 2021-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
    ]
