# Generated by Django 2.2 on 2021-04-05 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20210405_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
